apiVersion: v1
kind: Service
metadata:
  name: ops-demo
  namespace: ops-demo
  labels:
    app: ops-demo
spec:
  type: ClusterIP
  selector:
    app: ops-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
