apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-demo
  namespace: ops-demo
  labels:
    app: ops-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ops.host.docker.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ops-demo
                port:
                  number: 80
